#!/usr/bin/env sh

PWD_DIR=`pwd`

if [[ -f CMakeCache.txt && -f cmake_install.cmake && -d CMakeFiles && -f Makefile ]]; then
    echo "Blowing away working directory: '$PWD_DIR'"
    #read -p "Are you sure? " -n 1 -r
    #echo
    #if [[ $REPLY =~ ^[Yy]$ ]]
    #then
    rm -rf *
    #fi
else
    echo "Current directory doesn't seem to be a cmake build dir."
fi
